kumuluzee:
  name: sharing
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  config:
    etcd:
      hosts: http://etcd:2379
  health:
    checks:
      etcd-health-check:
        connection-url: http://etcd:2379/health
  metrics:
    web-instrumentation:
      - name: users-endpoint
        url-pattern: /v1/users/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="sharing">
                    <Appenders>
                      <Console name="console" target="SYSTEM_OUT">
                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                      </Console>
                      <Socket name="logstash" host="984fd9b0-06a6-4350-acbb-9a328652e786-ls.logit.io" port="16623"
                       protocol="tcp">
                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                      </Socket>
                    </Appenders>
                    <Loggers>
                      <Root level="all">
                        <AppenderRef ref="console" level="info"/>
                        <AppenderRef ref="logstash" level="trace"/>
                      </Root>
                    </Loggers>
                  </Configuration>'

configuration-properties:
  demo-etcd-parameter: file
  demo-service-is-healthy: true
  db-url: jdbc:mysql://10.67.0.3:3306/sharing
  db-user: root
  db-password: lPKKoBPxlnzhkkrn
  gcp-project: grmek-rso
  gcp-key: <hidden>
  gcp-storage-bucket: grmek-rso-storage-bucket
